### ISSUE TITLE
Create the initial model of the person class

### ISSUE THREAD

**Issue by alvarodelaflor** [alvarodelaflor/CoronaAlert#61]
A person must have at least the following attributes:
- Name
- Surname
- Is Professor 
- Age
- Phone number
- University
- Email
- Active

**isProfessor:** identify if this person is a teacher (isProfessor = true), or not.
**active:** differentiates between accounts that have been validated by the system (active=true) and those that have not

This issue is related to the user stories #57 #58

**Comment by JJ** [comment]
Issues should express problems, not actions.
